services:
  - type: web
    name: discord-bot-vending-machine
    env: node
    buildCommand: node render-build.js
    startCommand: NODE_ENV=production node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_FIREBASE
        value: true
      - key: PORT
        value: 10000