services:
  - type: web
    name: discord-vending-bot
    env: node
    buildCommand: ./build.sh
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DISCORD_BOT_TOKEN
        sync: false # このフラグはRenderダッシュボードでの手動設定が必要なことを示します
    autoDeploy: true # GitHubからの自動デプロイを有効化